name: doecerto

services:
  # --- BANCO DE DADOS ---
  db:
    image: mysql:8
    container_name: doecerto_db
    restart: always
    env_file:
      - .env            # Puxa DB_PASSWORD e DB_NAME da raiz
      - ./docker/db.env # Traduz para MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - doecerto_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  # --- CACHE ---
  redis:
    image: redis:7-alpine
    container_name: doecerto_redis
    restart: always
    command: redis-server --save 60 1 --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - doecerto_network
    volumes:
      - redis_data:/data

  # --- BACKEND ---
  api:
    image: guilhermemth/doecerto-api:latest
    container_name: doecerto_api
    restart: always
    env_file:
      - .env             # Segredos raiz
      - ./docker/api.env # Mapeamento NestJS/ConfigService
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: 
      - doecerto_network
    # Injetando o entrypoint que mora no repo de infra para dentro da imagem do back
    volumes:
      - uploads_profiles:/app/uploads/profiles
      - uploads_payments:/app/uploads/payment-proofs
      - api_logs:/app/logs
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # --- FRONTEND ---
  frontend:
    image: guilhermemth/doecerto-front:latest
    container_name: doecerto_frontend
    restart: always
    depends_on:
      - api
    networks:
      - doecerto_network
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # --- PROXY REVERSO (SSL AUTOMÁTICO) ---
  caddy:
    image: caddy:2-alpine
    container_name: doecerto_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MY_DOMAIN=${BACKEND_URL} # Puxa do .env (será o DNS da Azure)
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - doecerto_network
    depends_on:
      - frontend
      - api

  # --- ATUALIZAÇÃO AUTOMÁTICA ---
  watchtower:
    image: containrrr/watchtower:latest
    container_name: doecerto_watchtower
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --label-enable

networks:
  doecerto_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  caddy_data:
  caddy_config:
  uploads_profiles:
  uploads_payments:
  api_logs: