name: 'Deploy Infra e Apps'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      vm_ip: ${{ steps.set-ip.outputs.VM_IP }}
      vm_fqdn: ${{ steps.set-ip.outputs.VM_FQDN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init e Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Get VM Outputs
        id: set-ip
        run: |
          cd terraform
          # Captura o IP e o FQDN (DNS da Azure) para usar no deploy
          echo "VM_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
          echo "VM_FQDN=$(terraform output -raw backend_url_variable)" >> $GITHUB_OUTPUT

  deploy-docker:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # 1. Cria o arquivo com o que você colou no Secret DOT_ENV
          echo "${{ secrets.DOT_ENV }}" > .env
          
          # 2. (Opcional) Sobrescreve ou adiciona o domínio dinâmico da Azure
          # Isso garante que o MY_DOMAIN do Caddy esteja sempre certo
          echo "MY_DOMAIN=${{ needs.terraform.outputs.vm_fqdn }}" >> .env
          echo "VM_IP=${{ needs.terraform.outputs.vm_ip }}" >> .env

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.terraform.outputs.vm_ip }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # O arquivo .env criado acima será copiado agora
          source: "./docker-compose.yml,./docker,./.env,./Caddyfile"
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: Executing Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.terraform.outputs.vm_ip }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/app
            # Força o Docker a ler o novo .env e subir os containers
            docker compose pull
            docker compose up -d --remove-orphans